{
 "title": "Kafka Cluster / Global HealthCheck",
 "tags": [
  "kafka",
  "broker",
  "healthcheck"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(kafka_server_brokerstate, env)"
   }
  ]
 },
 "panels": [
  { "title": "Healthcheck", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controller",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_activecontrollercount{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable. Alert if value is greater than 0.",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_offlinepartitionscount{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |). Alert if value is greater than 0.",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replica_manager_underreplicatedpartitions{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Partitions Under Min ISR",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | min.insync.replicas  |). Alert if value is greater than 0.",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Preferred Replica Imbalance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_preferredreplicaimbalancecount{env=\"$env\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "content": "<img src=\"http://kafka.apache.org/images/logo.png\" alt=\"Apache Kafkas logo\" style=\"height: 80px;\">\n\n<p style=\"margin-top: 10px;\">You're using Apache Kafka, an open-source distributed and fault-tolerant streaming platform originally built at LinkedIn. For more information, check out the <a href=\"http://kafka.apache.org/\">kafka.apache.org</a>"
  },
  {
   "title": "Brokers Running(>=3)",
   "type": "singlestat",
   "description": "Total number of brokers with a state running (i.e 3)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((kafka_server_brokerstate{env=\"$env\"}) == 3 or (kafka_server_brokerstate{env=\"$env\"}) == 4)"
    }
   ]
  },
  {
   "title": "Produce Req Per Sec",
   "type": "singlestat",
   "description": "Total number of producer requests per second",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_network_request_per_sec{aggregate=~\"OneMinuteRate\",request=~\"Produce\",env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Fetch Consumer Req Per Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_network_request_per_sec{aggregate=~\"OneMinuteRate\",request=~\"FetchConsumer\",env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Metadata Req Per Sec",
   "type": "singlestat",
   "description": "Number of metadata requests per sec",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_network_request_per_sec{aggregate=~\"OneMinuteRate\",request=~\"Metadata\",env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Offset Commit Req Per Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_network_request_per_sec{aggregate=~\"OneMinuteRate\",request=~\"OffsetCommit\",env=\"$env\"})"
    }
   ]
  },
  { "title": "Throughput In/Out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Messages In Per Topics",
   "type": "graph",
   "description": "Aggregate incoming message rate.",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "wps", "label": "Msg/sec" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_broker_topic_metrics_messagesinpersec_rate{topic!=\"\"}) by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In per sec",
   "type": "singlestat",
   "description": "Aggregate incoming message rate.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_broker_topic_metrics_messagesinpersec_rate{topic=\"\"}) by (broker)"
    }
   ]
  },
  {
   "title": "Bytes In per sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 12 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_broker_topic_metrics_bytesinpersec_rate{topic=\"\"}) by (broker)"
    }
   ]
  },
  {
   "title": "Bytes Out per sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 16 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_broker_topic_metrics_bytesoutpersec_rate{topic=\"\"}) by (broker)"
    }
   ]
  }
 ]
}